### ISSUE TITLE
Wrong charcodes for form feed and carriage return ?

### ISSUE THREAD

**Issue by kidplug** [oberstet/pljson#1]
in json_printer:

```
when chr(13) then buf := '\f';
when chr(14) then buf := '\r';
```

Form feed \f should be code 12, and carriage return \r should be 13.

Maybe same issue in json_parser which is why it works?

```
        when 'f' then varbuf := varbuf || chr(13);
        when 'n' then varbuf := varbuf || chr(10);
        when 'r' then varbuf := varbuf || chr(14);
```

**Comment by oberstet** [comment]
Could be a bug, probably check with the upstream author at https://sourceforge.net/projects/pljson/ ? If it is a bug, we can fix it here also ..

**Comment by kidplug** [comment]
Looks like this issue is fixed in the new git plsql repo:
https://github.com/pljson/pljson
